id: PACE5A51A
initial_creation_type: input
source_metadata:
  title: Lodi Gyari Rinpoche
  language: es
  description: Texts by or related to Lodi Gyari Rinpoche, also known as Pema Lodrö
    Gyaltsen (padma blo gros rgyal mtshan, 1949–2018), who was the special envoy to
    His Holiness the Dalai Lama in Washington DC.
  volume:
    5e5e3833ac7844fcb91b4be2761b3c2f:
      title: Prayer to His Holiness the Dalai Lama
      parent: Prayers
    4e600f1bd3604d5eb8c16d4bc5eac6d6:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    4085fddfff6947658e6ccb050a3fbd7b:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Guru Rinpoche Prayers
    f78a6abd62f847d4b543120e0cbd2f68:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Dharma Protectors
created_at: '2022-03-01T00:39:16.899652'
last_modified_at: '2022-03-01T00:39:16.899655'
